export interface ResourceConfig {
  group: string
  version: string
  plural: string
  displayName: string
  namespaced: boolean
  /** Route category for sidebar grouping */
  category: 'workloads' | 'networking' | 'config' | 'storage' | 'rbac' | 'cluster' | 'custom'
}

export const RESOURCE_CONFIG: Record<string, ResourceConfig> = {
  pods: {
    group: '',
    version: 'v1',
    plural: 'pods',
    displayName: 'Pods',
    namespaced: true,
    category: 'workloads',
  },
  deployments: {
    group: 'apps',
    version: 'v1',
    plural: 'deployments',
    displayName: 'Deployments',
    namespaced: true,
    category: 'workloads',
  },
  statefulsets: {
    group: 'apps',
    version: 'v1',
    plural: 'statefulsets',
    displayName: 'StatefulSets',
    namespaced: true,
    category: 'workloads',
  },
  daemonsets: {
    group: 'apps',
    version: 'v1',
    plural: 'daemonsets',
    displayName: 'DaemonSets',
    namespaced: true,
    category: 'workloads',
  },
  replicasets: {
    group: 'apps',
    version: 'v1',
    plural: 'replicasets',
    displayName: 'ReplicaSets',
    namespaced: true,
    category: 'workloads',
  },
  jobs: {
    group: 'batch',
    version: 'v1',
    plural: 'jobs',
    displayName: 'Jobs',
    namespaced: true,
    category: 'workloads',
  },
  cronjobs: {
    group: 'batch',
    version: 'v1',
    plural: 'cronjobs',
    displayName: 'CronJobs',
    namespaced: true,
    category: 'workloads',
  },
  services: {
    group: '',
    version: 'v1',
    plural: 'services',
    displayName: 'Services',
    namespaced: true,
    category: 'networking',
  },
  ingresses: {
    group: 'networking.k8s.io',
    version: 'v1',
    plural: 'ingresses',
    displayName: 'Ingresses',
    namespaced: true,
    category: 'networking',
  },
  endpoints: {
    group: '',
    version: 'v1',
    plural: 'endpoints',
    displayName: 'Endpoints',
    namespaced: true,
    category: 'networking',
  },
  networkpolicies: {
    group: 'networking.k8s.io',
    version: 'v1',
    plural: 'networkpolicies',
    displayName: 'Network Policies',
    namespaced: true,
    category: 'networking',
  },
  configmaps: {
    group: '',
    version: 'v1',
    plural: 'configmaps',
    displayName: 'ConfigMaps',
    namespaced: true,
    category: 'config',
  },
  secrets: {
    group: '',
    version: 'v1',
    plural: 'secrets',
    displayName: 'Secrets',
    namespaced: true,
    category: 'config',
  },
  horizontalpodautoscalers: {
    group: 'autoscaling',
    version: 'v2',
    plural: 'horizontalpodautoscalers',
    displayName: 'Horizontal Pod Autoscalers',
    namespaced: true,
    category: 'config',
  },
  resourcequotas: {
    group: '',
    version: 'v1',
    plural: 'resourcequotas',
    displayName: 'Resource Quotas',
    namespaced: true,
    category: 'config',
  },
  limitranges: {
    group: '',
    version: 'v1',
    plural: 'limitranges',
    displayName: 'Limit Ranges',
    namespaced: true,
    category: 'config',
  },
  poddisruptionbudgets: {
    group: 'policy',
    version: 'v1',
    plural: 'poddisruptionbudgets',
    displayName: 'Pod Disruption Budgets',
    namespaced: true,
    category: 'config',
  },
  persistentvolumeclaims: {
    group: '',
    version: 'v1',
    plural: 'persistentvolumeclaims',
    displayName: 'Persistent Volume Claims',
    namespaced: true,
    category: 'storage',
  },
  persistentvolumes: {
    group: '',
    version: 'v1',
    plural: 'persistentvolumes',
    displayName: 'Persistent Volumes',
    namespaced: false,
    category: 'storage',
  },
  storageclasses: {
    group: 'storage.k8s.io',
    version: 'v1',
    plural: 'storageclasses',
    displayName: 'Storage Classes',
    namespaced: false,
    category: 'storage',
  },
  serviceaccounts: {
    group: '',
    version: 'v1',
    plural: 'serviceaccounts',
    displayName: 'Service Accounts',
    namespaced: true,
    category: 'rbac',
  },
  roles: {
    group: 'rbac.authorization.k8s.io',
    version: 'v1',
    plural: 'roles',
    displayName: 'Roles',
    namespaced: true,
    category: 'rbac',
  },
  clusterroles: {
    group: 'rbac.authorization.k8s.io',
    version: 'v1',
    plural: 'clusterroles',
    displayName: 'Cluster Roles',
    namespaced: false,
    category: 'rbac',
  },
  rolebindings: {
    group: 'rbac.authorization.k8s.io',
    version: 'v1',
    plural: 'rolebindings',
    displayName: 'Role Bindings',
    namespaced: true,
    category: 'rbac',
  },
  clusterrolebindings: {
    group: 'rbac.authorization.k8s.io',
    version: 'v1',
    plural: 'clusterrolebindings',
    displayName: 'Cluster Role Bindings',
    namespaced: false,
    category: 'rbac',
  },
  nodes: {
    group: '',
    version: 'v1',
    plural: 'nodes',
    displayName: 'Nodes',
    namespaced: false,
    category: 'cluster',
  },
  namespaces: {
    group: '',
    version: 'v1',
    plural: 'namespaces',
    displayName: 'Namespaces',
    namespaced: false,
    category: 'cluster',
  },
  events: {
    group: '',
    version: 'v1',
    plural: 'events',
    displayName: 'Events',
    namespaced: true,
    category: 'cluster',
  },
  priorityclasses: {
    group: 'scheduling.k8s.io',
    version: 'v1',
    plural: 'priorityclasses',
    displayName: 'Priority Classes',
    namespaced: false,
    category: 'cluster',
  },
  crds: {
    group: 'apiextensions.k8s.io',
    version: 'v1',
    plural: 'customresourcedefinitions',
    displayName: 'Custom Resource Definitions',
    namespaced: false,
    category: 'custom',
  },
}
