// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseAISession(arg1) {
  return window['go']['handlers']['AIHandler']['CloseAISession'](arg1);
}

export function CloseAll() {
  return window['go']['handlers']['AIHandler']['CloseAll']();
}

export function FindAIPath(arg1) {
  return window['go']['handlers']['AIHandler']['FindAIPath'](arg1);
}

export function GetAIProviderName() {
  return window['go']['handlers']['AIHandler']['GetAIProviderName']();
}

export function GetEnabledAIProviders() {
  return window['go']['handlers']['AIHandler']['GetEnabledAIProviders']();
}

export function ResizeAISession(arg1, arg2, arg3) {
  return window['go']['handlers']['AIHandler']['ResizeAISession'](arg1, arg2, arg3);
}

export function SetEmitter(arg1) {
  return window['go']['handlers']['AIHandler']['SetEmitter'](arg1);
}

export function StartAISession(arg1, arg2, arg3) {
  return window['go']['handlers']['AIHandler']['StartAISession'](arg1, arg2, arg3);
}

export function ValidateAIPath(arg1) {
  return window['go']['handlers']['AIHandler']['ValidateAIPath'](arg1);
}

export function WriteAISession(arg1, arg2) {
  return window['go']['handlers']['AIHandler']['WriteAISession'](arg1, arg2);
}
