// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcknowledgeAlert(arg1) {
  return window['go']['handlers']['AlertHandler']['AcknowledgeAlert'](arg1);
}

export function ActiveAlertCount() {
  return window['go']['handlers']['AlertHandler']['ActiveAlertCount']();
}

export function GetRules() {
  return window['go']['handlers']['AlertHandler']['GetRules']();
}

export function ListAlerts() {
  return window['go']['handlers']['AlertHandler']['ListAlerts']();
}
