// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAuditCount() {
  return window['go']['handlers']['AuditHandler']['GetAuditCount']();
}

export function GetAuditLog(arg1) {
  return window['go']['handlers']['AuditHandler']['GetAuditLog'](arg1);
}
