// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Export(arg1) {
  return window['go']['handlers']['BackupHandler']['Export'](arg1);
}

export function Import(arg1) {
  return window['go']['handlers']['BackupHandler']['Import'](arg1);
}

export function StripManifest(arg1) {
  return window['go']['handlers']['BackupHandler']['StripManifest'](arg1);
}
