// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActiveConnection() {
  return window['go']['handlers']['ClusterHandler']['ActiveConnection']();
}

export function CheckRBACPermission(arg1, arg2, arg3, arg4) {
  return window['go']['handlers']['ClusterHandler']['CheckRBACPermission'](arg1, arg2, arg3, arg4);
}

export function CheckRBACPermissions(arg1, arg2, arg3, arg4) {
  return window['go']['handlers']['ClusterHandler']['CheckRBACPermissions'](arg1, arg2, arg3, arg4);
}

export function Connect(arg1) {
  return window['go']['handlers']['ClusterHandler']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['handlers']['ClusterHandler']['Disconnect']();
}

export function GetClusterSummary() {
  return window['go']['handlers']['ClusterHandler']['GetClusterSummary']();
}

export function GetConnectionSnapshot() {
  return window['go']['handlers']['ClusterHandler']['GetConnectionSnapshot']();
}

export function GetMetrics() {
  return window['go']['handlers']['ClusterHandler']['GetMetrics']();
}

export function ListConnections() {
  return window['go']['handlers']['ClusterHandler']['ListConnections']();
}

export function ListContextDetails() {
  return window['go']['handlers']['ClusterHandler']['ListContextDetails']();
}

export function ListContexts() {
  return window['go']['handlers']['ClusterHandler']['ListContexts']();
}

export function ListNamespaces() {
  return window['go']['handlers']['ClusterHandler']['ListNamespaces']();
}

export function PreflightCheck(arg1) {
  return window['go']['handlers']['ClusterHandler']['PreflightCheck'](arg1);
}

export function SetKubeconfigPaths(arg1) {
  return window['go']['handlers']['ClusterHandler']['SetKubeconfigPaths'](arg1);
}

export function SwitchContext(arg1) {
  return window['go']['handlers']['ClusterHandler']['SwitchContext'](arg1);
}
