// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportConfig() {
  return window['go']['handlers']['ConfigHandler']['ExportConfig']();
}

export function GetConfig() {
  return window['go']['handlers']['ConfigHandler']['GetConfig']();
}

export function GetConfigPath() {
  return window['go']['handlers']['ConfigHandler']['GetConfigPath']();
}

export function ImportConfig(arg1) {
  return window['go']['handlers']['ConfigHandler']['ImportConfig'](arg1);
}

export function LoadFromFile(arg1) {
  return window['go']['handlers']['ConfigHandler']['LoadFromFile'](arg1);
}

export function ResetConfig() {
  return window['go']['handlers']['ConfigHandler']['ResetConfig']();
}

export function SaveToFile(arg1) {
  return window['go']['handlers']['ConfigHandler']['SaveToFile'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['handlers']['ConfigHandler']['UpdateConfig'](arg1);
}
