// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DetectClusterProviders() {
  return window['go']['handlers']['GitOpsHandler']['DetectClusterProviders']();
}

export function DetectProviders(arg1) {
  return window['go']['handlers']['GitOpsHandler']['DetectProviders'](arg1);
}
