// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddChartRepo(arg1, arg2) {
  return window['go']['handlers']['HelmHandler']['AddChartRepo'](arg1, arg2);
}

export function GetRelease(arg1, arg2) {
  return window['go']['handlers']['HelmHandler']['GetRelease'](arg1, arg2);
}

export function GetReleaseHistory(arg1, arg2) {
  return window['go']['handlers']['HelmHandler']['GetReleaseHistory'](arg1, arg2);
}

export function InstallChart(arg1, arg2, arg3, arg4) {
  return window['go']['handlers']['HelmHandler']['InstallChart'](arg1, arg2, arg3, arg4);
}

export function ListChartRepos() {
  return window['go']['handlers']['HelmHandler']['ListChartRepos']();
}

export function ListReleases(arg1) {
  return window['go']['handlers']['HelmHandler']['ListReleases'](arg1);
}

export function RemoveChartRepo(arg1) {
  return window['go']['handlers']['HelmHandler']['RemoveChartRepo'](arg1);
}

export function RollbackRelease(arg1, arg2, arg3) {
  return window['go']['handlers']['HelmHandler']['RollbackRelease'](arg1, arg2, arg3);
}

export function SearchCharts(arg1) {
  return window['go']['handlers']['HelmHandler']['SearchCharts'](arg1);
}

export function SetCluster(arg1, arg2) {
  return window['go']['handlers']['HelmHandler']['SetCluster'](arg1, arg2);
}

export function UninstallRelease(arg1, arg2) {
  return window['go']['handlers']['HelmHandler']['UninstallRelease'](arg1, arg2);
}

export function UpgradeChart(arg1, arg2, arg3, arg4) {
  return window['go']['handlers']['HelmHandler']['UpgradeChart'](arg1, arg2, arg3, arg4);
}
