// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildClusterNetworkGraph(arg1) {
  return window['go']['handlers']['NetPolHandler']['BuildClusterNetworkGraph'](arg1);
}

export function BuildNetworkGraph(arg1, arg2) {
  return window['go']['handlers']['NetPolHandler']['BuildNetworkGraph'](arg1, arg2);
}
