// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildClusterRBACGraph() {
  return window['go']['handlers']['RBACHandler']['BuildClusterRBACGraph']();
}

export function BuildRBACGraph(arg1, arg2, arg3, arg4) {
  return window['go']['handlers']['RBACHandler']['BuildRBACGraph'](arg1, arg2, arg3, arg4);
}
