// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNodeTaint(arg1, arg2, arg3, arg4) {
  return window['go']['handlers']['ResourceHandler']['AddNodeTaint'](arg1, arg2, arg3, arg4);
}

export function ApplyResource(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['handlers']['ResourceHandler']['ApplyResource'](arg1, arg2, arg3, arg4, arg5);
}

export function BatchDelete(arg1) {
  return window['go']['handlers']['ResourceHandler']['BatchDelete'](arg1);
}

export function CordonNode(arg1) {
  return window['go']['handlers']['ResourceHandler']['CordonNode'](arg1);
}

export function CreateJobFromCronJob(arg1, arg2, arg3) {
  return window['go']['handlers']['ResourceHandler']['CreateJobFromCronJob'](arg1, arg2, arg3);
}

export function DeleteResource(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['handlers']['ResourceHandler']['DeleteResource'](arg1, arg2, arg3, arg4, arg5);
}

export function DrainNode(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['handlers']['ResourceHandler']['DrainNode'](arg1, arg2, arg3, arg4, arg5);
}

export function DryRunApply(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['handlers']['ResourceHandler']['DryRunApply'](arg1, arg2, arg3, arg4, arg5);
}

export function GetPodMetrics(arg1) {
  return window['go']['handlers']['ResourceHandler']['GetPodMetrics'](arg1);
}

export function GetResource(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['handlers']['ResourceHandler']['GetResource'](arg1, arg2, arg3, arg4, arg5);
}

export function GetRolloutHistory(arg1, arg2) {
  return window['go']['handlers']['ResourceHandler']['GetRolloutHistory'](arg1, arg2);
}

export function ListEvents(arg1, arg2) {
  return window['go']['handlers']['ResourceHandler']['ListEvents'](arg1, arg2);
}

export function ListResources(arg1, arg2, arg3, arg4) {
  return window['go']['handlers']['ResourceHandler']['ListResources'](arg1, arg2, arg3, arg4);
}

export function PatchLabels(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['handlers']['ResourceHandler']['PatchLabels'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function PatchServiceSelector(arg1, arg2, arg3) {
  return window['go']['handlers']['ResourceHandler']['PatchServiceSelector'](arg1, arg2, arg3);
}

export function PauseDeployment(arg1, arg2) {
  return window['go']['handlers']['ResourceHandler']['PauseDeployment'](arg1, arg2);
}

export function RemoveNodeTaint(arg1, arg2) {
  return window['go']['handlers']['ResourceHandler']['RemoveNodeTaint'](arg1, arg2);
}

export function RestartDeployment(arg1, arg2) {
  return window['go']['handlers']['ResourceHandler']['RestartDeployment'](arg1, arg2);
}

export function ResumeDeployment(arg1, arg2) {
  return window['go']['handlers']['ResourceHandler']['ResumeDeployment'](arg1, arg2);
}

export function ScaleDeployment(arg1, arg2, arg3) {
  return window['go']['handlers']['ResourceHandler']['ScaleDeployment'](arg1, arg2, arg3);
}

export function SetAlertStore(arg1) {
  return window['go']['handlers']['ResourceHandler']['SetAlertStore'](arg1);
}

export function SetAuditLogger(arg1) {
  return window['go']['handlers']['ResourceHandler']['SetAuditLogger'](arg1);
}

export function SetEmitter(arg1) {
  return window['go']['handlers']['ResourceHandler']['SetEmitter'](arg1);
}

export function SetTimeline(arg1) {
  return window['go']['handlers']['ResourceHandler']['SetTimeline'](arg1);
}

export function StopWatch(arg1, arg2, arg3, arg4) {
  return window['go']['handlers']['ResourceHandler']['StopWatch'](arg1, arg2, arg3, arg4);
}

export function UncordonNode(arg1) {
  return window['go']['handlers']['ResourceHandler']['UncordonNode'](arg1);
}

export function WatchResources(arg1, arg2, arg3, arg4) {
  return window['go']['handlers']['ResourceHandler']['WatchResources'](arg1, arg2, arg3, arg4);
}
