// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSecret(arg1, arg2) {
  return window['go']['handlers']['SecretHandler']['GetSecret'](arg1, arg2);
}

export function RevealSecretKey(arg1, arg2, arg3) {
  return window['go']['handlers']['SecretHandler']['RevealSecretKey'](arg1, arg2, arg3);
}
