// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPodSecurity(arg1) {
  return window['go']['handlers']['SecurityScanHandler']['CheckPodSecurity'](arg1);
}

export function ScanAllPods(arg1) {
  return window['go']['handlers']['SecurityScanHandler']['ScanAllPods'](arg1);
}
