// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseExec(arg1) {
  return window['go']['handlers']['StreamHandler']['CloseExec'](arg1);
}

export function DownloadLogs(arg1) {
  return window['go']['handlers']['StreamHandler']['DownloadLogs'](arg1);
}

export function ListPortForwards() {
  return window['go']['handlers']['StreamHandler']['ListPortForwards']();
}

export function SetEmitter(arg1) {
  return window['go']['handlers']['StreamHandler']['SetEmitter'](arg1);
}

export function StartExec(arg1) {
  return window['go']['handlers']['StreamHandler']['StartExec'](arg1);
}

export function StartPortForward(arg1) {
  return window['go']['handlers']['StreamHandler']['StartPortForward'](arg1);
}

export function StartServicePortForward(arg1, arg2, arg3, arg4) {
  return window['go']['handlers']['StreamHandler']['StartServicePortForward'](arg1, arg2, arg3, arg4);
}

export function StopAllContainerLogs(arg1, arg2) {
  return window['go']['handlers']['StreamHandler']['StopAllContainerLogs'](arg1, arg2);
}

export function StopLogStream(arg1, arg2) {
  return window['go']['handlers']['StreamHandler']['StopLogStream'](arg1, arg2);
}

export function StopPortForward(arg1) {
  return window['go']['handlers']['StreamHandler']['StopPortForward'](arg1);
}

export function StreamAllContainerLogs(arg1, arg2, arg3, arg4) {
  return window['go']['handlers']['StreamHandler']['StreamAllContainerLogs'](arg1, arg2, arg3, arg4);
}

export function StreamLogs(arg1) {
  return window['go']['handlers']['StreamHandler']['StreamLogs'](arg1);
}

export function WriteExec(arg1, arg2) {
  return window['go']['handlers']['StreamHandler']['WriteExec'](arg1, arg2);
}
