// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTemplate(arg1) {
  return window['go']['handlers']['TemplateHandler']['DeleteTemplate'](arg1);
}

export function ListTemplates() {
  return window['go']['handlers']['TemplateHandler']['ListTemplates']();
}

export function RenderTemplate(arg1, arg2) {
  return window['go']['handlers']['TemplateHandler']['RenderTemplate'](arg1, arg2);
}

export function SaveTemplate(arg1) {
  return window['go']['handlers']['TemplateHandler']['SaveTemplate'](arg1);
}
