// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRecentChanges() {
  return window['go']['handlers']['TroubleshootHandler']['GetRecentChanges']();
}

export function GetTimeline(arg1, arg2, arg3) {
  return window['go']['handlers']['TroubleshootHandler']['GetTimeline'](arg1, arg2, arg3);
}

export function Investigate(arg1, arg2, arg3, arg4) {
  return window['go']['handlers']['TroubleshootHandler']['Investigate'](arg1, arg2, arg3, arg4);
}

export function InvestigateResource(arg1, arg2, arg3) {
  return window['go']['handlers']['TroubleshootHandler']['InvestigateResource'](arg1, arg2, arg3);
}
