// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['handlers']['UpdateHandler']['CheckForUpdate']();
}

export function SkipVersion(arg1) {
  return window['go']['handlers']['UpdateHandler']['SkipVersion'](arg1);
}
