// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PreviewConfigMap(arg1) {
  return window['go']['handlers']['WizardHandler']['PreviewConfigMap'](arg1);
}

export function PreviewDeployment(arg1) {
  return window['go']['handlers']['WizardHandler']['PreviewDeployment'](arg1);
}

export function PreviewSecret(arg1) {
  return window['go']['handlers']['WizardHandler']['PreviewSecret'](arg1);
}

export function PreviewService(arg1) {
  return window['go']['handlers']['WizardHandler']['PreviewService'](arg1);
}
